spring:
  application:
    name: wms
  #    druid数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: "040712"
server:
  port: 8090
#      mybatis相关配置
mybatis:
  #  替代settings
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #    pojo别名
  type-aliases-package: com.zminder.wms.pojo
  #  XxxMapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql            # 指定环境为MySQL
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.zminder.wms.mapper: debug